site_name: '🧪 The MLOps Cookbook'
repo_url: https://github.com/Matesanz/mlops-cookbook
repo_name: Matesanz/mlops-cookbook
site_url: https://matesanz.github.io/mlops-cookbook/
theme:
  name: material
  theme:
  palette:
    primary: teal
  features:
    - content.code.annotate
    - navigation.sections
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
  custom_dir: "docs/overrides"

plugins:
  - search
  - autorefs
  - awesome-pages
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
  - mkdocs-jupyter:
      include_source: True


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
    - Getting Started:
      - index.md
      - about.md
    - MLFlow:
      - mlflow/index.md
      - MLFlow Basics:
        - mlflow/basics/1-connect_to_mlflow.ipynb
        - mlflow/basics/2-creating_an_experiment.ipynb
        - mlflow/basics/3-creating_a_run.ipynb
      - Model Tracking:
        - mlflow/tracking/4-logging_metrics.ipynb
        - mlflow/tracking/5-logging_artifacts.ipynb
        - mlflow/tracking/6-logging_models.ipynb
        - mlflow/tracking/7-autologging.ipynb
      - Model Registry:
        - mlflow/registry/index.md
        - mlflow/registry/8-register_model_ui.md
        - mlflow/registry/8-register_model_api.ipynb
        - mlflow/registry/9-tag_model_ui.md
        - mlflow/registry/9-tag_model_api.ipynb
      - Model Deployment:
        - mlflow/deployment/index.md
        - mlflow/deployment/10-deploy_model_locally.md
        - mlflow/deployment/10-deploy_model_docker.md
      - Model Invocation:
        - mlflow/invocation/index.md
        - mlflow/invocation/calling_a_model_api.ipynb
    - Fundamentals:
      - fundamentals/intro_to_git.md
      - fundamentals/intro_to_api.md
      - fundamentals/intro_to_virtual_environments.md
      - fundamentals/intro_to_docker.md
      - fundamentals/intro_to_poetry.md
    - Tutorials:
      - tutorials/index.md
      - tutorials/basic_model_tracking.ipynb
      # - tutorials/1-full_model_training.ipynb
      # - tutorials/2-full_model_evaluation.ipynb
    - Exercises:
      - exercises/index.md
      - exercises/1-intro_to_mlflow_I.ipynb
      - exercises/2-intro_to_mlflow_II.ipynb
      - exercises/3-intro_to_mlflow_III.ipynb
      - exercises/4-intro_to_mlflow_IV.ipynb
      - exercises/5-mlflow_for_kaggle_I.ipynb
      # - exercises/creating_a_docker_image.md

watch:
  - docs
